BACKGROUND_MODE = 'BACKGROUND'
ACTIVE_MODE = 'ACTIVE'
ALERT_MODE = 'ALERT'
CALL_MODE = 'CALL'

MODEL_FOLDER = 'model_folder'
CALLBACK = 'callback'

DEFAULT_SENSITIVITY = 0.5
DEFAULT_REPEAT_TIMEOUT = 5
DEFAULT_REPEAT_NUMBER = 2


OK_SAAM = 'OK SAAM'
HELP = 'HELP'
STOP = 'STOP'
HELP_REPEAT = 'HELP REPEAT'
CALL = 'CALL'
ERROR = 'ERROR'
CALL_FAMILY = 'CALL FAMILY'
CALL_NEIGHBOUR = 'CALL NEIGHBOUR'
REPEAT_COMMAND = 'REPEAT COMMAND'
